<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="87" failures="25" errors="0" time="85.856967">
	<testsuite tests="0" failures="0" time="0.003000" name="pkg.world.dev/world-cli/cmd/world" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/cmd/world/cardinal" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.003000" name="pkg.world.dev/world-cli/cmd/world/evm" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="25" failures="25" time="0.023000" name="pkg.world.dev/world-cli/cmd/world/forge" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestCreateOrganization" time="0.010000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestCreateOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestCreateOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 21 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00024ddc0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00024ddc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00024ddc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00024ddc0}, {0xd2e8c0, 0xc000229c20}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000209ae0, {0xd2e8c0, 0xc000229c20}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00024ddc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00024ddc0, 0xc0001d0360)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestCreateOrganization (0.01s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestCreateProject" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestCreateProject&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestCreateProject&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 22 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025a1c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025a1c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025a1c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025a1c0}, {0xd2e8c0, 0xc000229d10}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000209c20, {0xd2e8c0, 0xc000229d10}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025a1c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025a1c0, 0xc0001d03f0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestCreateProject (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestDeploy" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestDeploy&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestDeploy&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 23 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025a380, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025a380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025a380)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025a380}, {0xd2e8c0, 0xc000229e00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000209d40, {0xd2e8c0, 0xc000229e00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025a380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025a380, 0xc0001d0480)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestDeploy (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestDestroy" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestDestroy&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestDestroy&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 24 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025a540, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025a540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025a540)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025a540}, {0xd2e8c0, 0xc000229ef0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000209e60, {0xd2e8c0, 0xc000229ef0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025a540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025a540, 0xc0001d0510)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestDestroy (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestFindGitPathAndURL" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestFindGitPathAndURL&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestFindGitPathAndURL&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 25 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025a700, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025a700)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025a700)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025a700}, {0xd2e8c0, 0xc0002940a0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a000, {0xd2e8c0, 0xc0002940a0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025a700)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025a700, 0xc0001d05a0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestFindGitPathAndURL (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetInput" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetInput&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetInput&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 26 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025a8c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025a8c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025a8c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025a8c0}, {0xd2e8c0, 0xc000294190}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a120, {0xd2e8c0, 0xc000294190}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025a8c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025a8c0, 0xc0001d0630)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetInput (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetListOfProjects" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetListOfProjects&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetListOfProjects&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 27 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025aa80, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025aa80)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025aa80)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025aa80}, {0xd2e8c0, 0xc000294280}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a240, {0xd2e8c0, 0xc000294280}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025aa80)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025aa80, 0xc0001d06c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetListOfProjects (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetRoleInput" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetRoleInput&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetRoleInput&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 28 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025ac40, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025ac40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025ac40)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025ac40}, {0xd2e8c0, 0xc000294370}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a360, {0xd2e8c0, 0xc000294370}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025ac40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025ac40, 0xc0001d0750)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetRoleInput (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetSelectedOrganization" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetSelectedOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetSelectedOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 29 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025ae00, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025ae00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025ae00)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025ae00}, {0xd2e8c0, 0xc000294460}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a480, {0xd2e8c0, 0xc000294460}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025ae00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025ae00, 0xc0001d07e0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetSelectedOrganization (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetSelectedProject" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetSelectedProject&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetSelectedProject&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 30 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025afc0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025afc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025afc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025afc0}, {0xd2e8c0, 0xc000294550}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a5a0, {0xd2e8c0, 0xc000294550}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025afc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025afc0, 0xc0001d0870)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetSelectedProject (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestInviteUserToOrganization" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestInviteUserToOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestInviteUserToOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 31 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025b180, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025b180)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025b180)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025b180}, {0xd2e8c0, 0xc000294640}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a6c0, {0xd2e8c0, 0xc000294640}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025b180)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025b180, 0xc0001d0900)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestInviteUserToOrganization (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestIsAlphanumeric" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestIsAlphanumeric&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestIsAlphanumeric&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 32 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025b340, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025b340)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025b340)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025b340}, {0xd2e8c0, 0xc000294730}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a7e0, {0xd2e8c0, 0xc000294730}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025b340)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025b340, 0xc0001d0990)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestIsAlphanumeric (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestLogin" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestLogin&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestLogin&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 33 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025b500, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025b500)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025b500)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025b500}, {0xd2e8c0, 0xc000294820}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029a900, {0xd2e8c0, 0xc000294820}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025b500)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025b500, 0xc0001d0a20)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestLogin (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestOrganizationOperations" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestOrganizationOperations&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestOrganizationOperations&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 34 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025b6c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025b6c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025b6c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025b6c0}, {0xd2e8c0, 0xc000294910}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029aa20, {0xd2e8c0, 0xc000294910}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025b6c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025b6c0, 0xc0001d0ab0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestOrganizationOperations (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestParseResponse" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestParseResponse&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestParseResponse&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 35 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025b880, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025b880)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025b880)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025b880}, {0xd2e8c0, 0xc000294a00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029ab40, {0xd2e8c0, 0xc000294a00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025b880)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025b880, 0xc0001d0b40)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestParseResponse (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestReset" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestReset&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestReset&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 36 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025ba40, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025ba40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025ba40)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025ba40}, {0xd2e8c0, 0xc000294af0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029ac60, {0xd2e8c0, 0xc000294af0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025ba40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025ba40, 0xc0001d0bd0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestReset (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestSelectProject" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestSelectProject&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestSelectProject&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 37 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025bc00, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025bc00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025bc00)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025bc00}, {0xd2e8c0, 0xc000294be0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029ad80, {0xd2e8c0, 0xc000294be0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025bc00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025bc00, 0xc0001d0c60)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestSelectProject (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestShowOrganizationList" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestShowOrganizationList&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestShowOrganizationList&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 38 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00025bdc0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00025bdc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00025bdc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00025bdc0}, {0xd2e8c0, 0xc000294cd0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029aea0, {0xd2e8c0, 0xc000294cd0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00025bdc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00025bdc0, 0xc0001d0cf0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestShowOrganizationList (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestShowProjectList" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestShowProjectList&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestShowProjectList&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 39 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00031e000, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00031e000)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00031e000)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00031e000}, {0xd2e8c0, 0xc000294dc0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029afc0, {0xd2e8c0, 0xc000294dc0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00031e000)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00031e000, 0xc0001d0d80)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestShowProjectList (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestSlugCreateFromName" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestSlugCreateFromName&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestSlugCreateFromName&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 40 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00031e1c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00031e1c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00031e1c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00031e1c0}, {0xd2e8c0, 0xc000294eb0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029b0e0, {0xd2e8c0, 0xc000294eb0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00031e1c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00031e1c0, 0xc0001d0e10)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestSlugCreateFromName (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestStatus" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestStatus&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestStatus&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 41 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00031e380, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00031e380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00031e380)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00031e380}, {0xd2e8c0, 0xc000294fa0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029b200, {0xd2e8c0, 0xc000294fa0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00031e380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00031e380, 0xc0001d0ea0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestStatus (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestUpdateRoleInOrganization" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestUpdateRoleInOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestUpdateRoleInOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 42 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00031e540, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00031e540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00031e540)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00031e540}, {0xd2e8c0, 0xc000295090}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029b320, {0xd2e8c0, 0xc000295090}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00031e540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00031e540, 0xc0001d0f30)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestUpdateRoleInOrganization (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestValidateRepoPath" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestValidateRepoPath&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestValidateRepoPath&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 43 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00031e700, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00031e700)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00031e700)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00031e700}, {0xd2e8c0, 0xc000295180}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029b440, {0xd2e8c0, 0xc000295180}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00031e700)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00031e700, 0xc0001d0fc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestValidateRepoPath (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestValidateRepoToken" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestValidateRepoToken&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestValidateRepoToken&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 44 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc00031e8c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc00031e8c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc00031e8c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc00031e8c0}, {0xd2e8c0, 0xc000295270}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc00029b560, {0xd2e8c0, 0xc000295270}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc0001b8700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc00031e8c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc00031e8c0, 0xc0001d1050)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 20&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestValidateRepoToken (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite" time="0.010000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite&#xA;--- FAIL: TestForgeSuite (0.01s)&#xA;</failure>
		</testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/cmd/world/root" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="8" failures="0" time="84.599000" name="pkg.world.dev/world-cli/cmd/world/root/testing" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestSubcommandsHaveHelpText" time="0.190000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestExecuteDoctorCommand" time="0.300000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestCreateStartStopRestartPurge" time="75.410000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestDev" time="4.630000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestCheckLatestVersion/success_scenario" time="0.030000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestCheckLatestVersion/error_version_format" time="0.030000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestCheckLatestVersion" time="0.060000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root/testing" name="TestEVMStart" time="3.660000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.005000" name="pkg.world.dev/world-cli/common" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="14" failures="0" time="0.010000" name="pkg.world.dev/world-cli/common/config" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanSetNamespaceWithFilename" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanSetNamespaceWithEnvVariable" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestConfigPreference" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestConfigFromLocalFile" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestLoadConfigLooksInParentDirectories" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestTextDecoding" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanSetArbitraryEnvVariables" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanOverrideRootDir" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestErrorWhenNoConfigFileExists" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestNumbersAreValidDockerEnvVariable" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestErrorOnInvalidToml" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestDuplicateEnvironmentVariableProducesError" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanParseExampleConfig" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestConfigFlagCannotBeEmpty" time="0.000000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.005000" name="pkg.world.dev/world-cli/common/dependency" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="6" failures="0" time="15.696000" name="pkg.world.dev/world-cli/common/docker" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestStart" time="2.070000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestStop" time="2.580000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestRestart" time="5.520000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestPurge" time="1.780000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestStartUndetach" time="3.080000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestBuild" time="0.610000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.006000" name="pkg.world.dev/world-cli/common/docker/service" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="16" failures="0" time="0.575000" name="pkg.world.dev/world-cli/common/editor" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestSetupCardinalEditor/setup_cardinal_editor" time="0.560000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestSetupCardinalEditor" time="0.560000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestCopyDir/Test_copy_directory" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestCopyDir" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestStrippedGUID/Test_guid_doesn&#39;t_contain_-" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestStrippedGUID" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestAddFileVersion" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion/Module_exists" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion/Module_does_not_exist" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion/go.mod_file_does_not_exist" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestFileExists" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap/successful_response_with_specific_version_map" time="0.010000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap/HTTP_error" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap/invalid_JSON" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap" time="0.010000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/common/globalconfig" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.005000" name="pkg.world.dev/world-cli/common/logger" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="1" failures="0" time="0.005000" name="pkg.world.dev/world-cli/common/login" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/login" name="TestDecryptAccessToken" time="0.000000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/common/printer" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="11" failures="0" time="0.637000" name="pkg.world.dev/world-cli/common/teacmd" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGitCloneCmd/error_clone_wrong_address" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGitCloneCmd/success" time="0.630000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGitCloneCmd" time="0.630000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml/append_first_section_and_fields" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml/append_fields_to_existing_section" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml/create_new_section_and_append_fields" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString/length_0" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString/length_8" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString/length_16" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString" time="0.000000"></testcase>
	</testsuite>
	<testsuite tests="6" failures="0" time="0.012000" name="pkg.world.dev/world-cli/common/tomlutil" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestCreateTOMLFile" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestGetTOMLSection" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestReadTOML" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestUpdateTOMLSection" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestWriteTOML" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite" time="0.010000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.005000" name="pkg.world.dev/world-cli/gen/logs/v1" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/gen/logs/v1/logsv1connect" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.005000" name="pkg.world.dev/world-cli/tea/component" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/tea/component/multiselect" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/tea/component/multispinner" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.007000" name="pkg.world.dev/world-cli/tea/component/program" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.007000" name="pkg.world.dev/world-cli/tea/component/spinner" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.007000" name="pkg.world.dev/world-cli/tea/component/steps" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.007000" name="pkg.world.dev/world-cli/tea/style" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.007000" name="pkg.world.dev/world-cli/telemetry" timestamp="2025-05-06T14:06:20-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
</testsuites>