<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="83" failures="28" errors="0" time="118.175060">
	<testsuite tests="0" failures="0" time="0.016000" name="pkg.world.dev/world-cli/cmd/world" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.015000" name="pkg.world.dev/world-cli/cmd/world/cardinal" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.015000" name="pkg.world.dev/world-cli/cmd/world/evm" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="25" failures="25" time="0.021000" name="pkg.world.dev/world-cli/cmd/world/forge" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestCreateOrganization" time="0.010000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestCreateOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestCreateOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 37 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0002cda40, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0002cda40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0002cda40)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0002cda40}, {0xd2e8c0, 0xc0002a9c20}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000289ae0, {0xd2e8c0, 0xc0002a9c20}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0002cda40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0002cda40, 0xc000248360)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestCreateOrganization (0.01s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestCreateProject" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestCreateProject&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestCreateProject&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 38 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0002cddc0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0002cddc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0002cddc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0002cddc0}, {0xd2e8c0, 0xc0002a9d10}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000289c20, {0xd2e8c0, 0xc0002a9d10}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0002cddc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0002cddc0, 0xc0002483f0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestCreateProject (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestDeploy" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestDeploy&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestDeploy&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 39 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308000, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308000)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308000)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308000}, {0xd2e8c0, 0xc0002a9e00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000289d40, {0xd2e8c0, 0xc0002a9e00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308000)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308000, 0xc000248480)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestDeploy (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestDestroy" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestDestroy&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestDestroy&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 40 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0003081c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0003081c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0003081c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0003081c0}, {0xd2e8c0, 0xc0002a9ef0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000289e60, {0xd2e8c0, 0xc0002a9ef0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0003081c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0003081c0, 0xc000248510)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestDestroy (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestFindGitPathAndURL" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestFindGitPathAndURL&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestFindGitPathAndURL&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 41 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308380, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308380)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308380}, {0xd2e8c0, 0xc0003120a0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318000, {0xd2e8c0, 0xc0003120a0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308380, 0xc0002485a0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestFindGitPathAndURL (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetInput" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetInput&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetInput&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 42 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308540, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308540)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308540}, {0xd2e8c0, 0xc000312190}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318120, {0xd2e8c0, 0xc000312190}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308540, 0xc000248630)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetInput (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetListOfProjects" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetListOfProjects&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetListOfProjects&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 43 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308700, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308700)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308700)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308700}, {0xd2e8c0, 0xc000312280}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318240, {0xd2e8c0, 0xc000312280}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308700)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308700, 0xc0002486c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetListOfProjects (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetRoleInput" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetRoleInput&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetRoleInput&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 44 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0003088c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0003088c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0003088c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0003088c0}, {0xd2e8c0, 0xc000312370}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318360, {0xd2e8c0, 0xc000312370}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0003088c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0003088c0, 0xc000248750)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetRoleInput (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetSelectedOrganization" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetSelectedOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetSelectedOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 45 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308a80, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308a80)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308a80)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308a80}, {0xd2e8c0, 0xc000312460}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318480, {0xd2e8c0, 0xc000312460}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308a80)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308a80, 0xc0002487e0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetSelectedOrganization (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestGetSelectedProject" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestGetSelectedProject&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestGetSelectedProject&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 46 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308c40, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308c40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308c40)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308c40}, {0xd2e8c0, 0xc000312550}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc0003185a0, {0xd2e8c0, 0xc000312550}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308c40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308c40, 0xc000248870)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestGetSelectedProject (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestInviteUserToOrganization" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestInviteUserToOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestInviteUserToOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 47 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308e00, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308e00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308e00)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308e00}, {0xd2e8c0, 0xc000312640}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc0003186c0, {0xd2e8c0, 0xc000312640}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308e00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308e00, 0xc000248900)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestInviteUserToOrganization (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestIsAlphanumeric" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestIsAlphanumeric&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestIsAlphanumeric&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 48 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000308fc0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000308fc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000308fc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000308fc0}, {0xd2e8c0, 0xc000312730}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc0003187e0, {0xd2e8c0, 0xc000312730}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000308fc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000308fc0, 0xc000248990)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestIsAlphanumeric (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestLogin" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestLogin&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestLogin&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 49 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000309180, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000309180)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000309180)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000309180}, {0xd2e8c0, 0xc000312820}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318900, {0xd2e8c0, 0xc000312820}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000309180)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000309180, 0xc000248a20)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestLogin (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestOrganizationOperations" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestOrganizationOperations&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestOrganizationOperations&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 50 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000309340, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000309340)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000309340)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000309340}, {0xd2e8c0, 0xc000312910}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318a20, {0xd2e8c0, 0xc000312910}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000309340)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000309340, 0xc000248ab0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestOrganizationOperations (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestParseResponse" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestParseResponse&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestParseResponse&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 51 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000309500, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000309500)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000309500)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000309500}, {0xd2e8c0, 0xc000312a00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318b40, {0xd2e8c0, 0xc000312a00}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000309500)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000309500, 0xc000248b40)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestParseResponse (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestReset" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestReset&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestReset&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 52 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0003096c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0003096c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0003096c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0003096c0}, {0xd2e8c0, 0xc000312af0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318c60, {0xd2e8c0, 0xc000312af0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0003096c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0003096c0, 0xc000248bd0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestReset (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestSelectProject" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestSelectProject&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestSelectProject&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 53 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000309880, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000309880)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000309880)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000309880}, {0xd2e8c0, 0xc000312be0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318d80, {0xd2e8c0, 0xc000312be0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000309880)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000309880, 0xc000248c60)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestSelectProject (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestShowOrganizationList" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestShowOrganizationList&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestShowOrganizationList&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 54 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000309a40, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000309a40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000309a40)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000309a40}, {0xd2e8c0, 0xc000312cd0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318ea0, {0xd2e8c0, 0xc000312cd0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000309a40)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000309a40, 0xc000248cf0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestShowOrganizationList (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestShowProjectList" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestShowProjectList&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestShowProjectList&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 55 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000309c00, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000309c00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000309c00)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000309c00}, {0xd2e8c0, 0xc000312dc0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000318fc0, {0xd2e8c0, 0xc000312dc0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000309c00)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000309c00, 0xc000248d80)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestShowProjectList (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestSlugCreateFromName" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestSlugCreateFromName&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestSlugCreateFromName&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 56 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc000309dc0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc000309dc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc000309dc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc000309dc0}, {0xd2e8c0, 0xc000312eb0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc0003190e0, {0xd2e8c0, 0xc000312eb0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc000309dc0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc000309dc0, 0xc000248e10)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestSlugCreateFromName (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestStatus" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestStatus&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestStatus&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 57 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0003b2000, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0003b2000)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0003b2000)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0003b2000}, {0xd2e8c0, 0xc000312fa0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000319200, {0xd2e8c0, 0xc000312fa0}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0003b2000)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0003b2000, 0xc000248ea0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestStatus (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestUpdateRoleInOrganization" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestUpdateRoleInOrganization&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestUpdateRoleInOrganization&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 58 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0003b21c0, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0003b21c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0003b21c0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0003b21c0}, {0xd2e8c0, 0xc000313090}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000319320, {0xd2e8c0, 0xc000313090}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0003b21c0)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0003b21c0, 0xc000248f30)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestUpdateRoleInOrganization (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestValidateRepoPath" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestValidateRepoPath&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestValidateRepoPath&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 59 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0003b2380, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0003b2380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0003b2380)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0003b2380}, {0xd2e8c0, 0xc000313180}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000319440, {0xd2e8c0, 0xc000313180}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0003b2380)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0003b2380, 0xc000248fc0)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestValidateRepoPath (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite/TestValidateRepoToken" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite/TestValidateRepoToken&#xA;    forge_test.go:54: &#xA;        &#x9;Error Trace:&#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54&#xA;        &#x9;            &#x9;&#x9;&#x9;&#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192&#xA;        &#x9;Error:      &#x9;Received unexpected error:&#xA;        &#x9;            &#x9;listen tcp :8001: bind: address already in use&#xA;        &#x9;Test:       &#x9;TestForgeSuite/TestValidateRepoToken&#xA;    panic.go:262: test panicked: runtime error: invalid memory address or nil pointer dereference&#xA;        goroutine 60 [running]:&#xA;        runtime/debug.Stack()&#xA;        &#x9;/usr/local/go/src/runtime/debug/stack.go:26 +0x5e&#xA;        github.com/stretchr/testify/suite.failOnPanic(0xc0003b2540, {0xb5a3c0, 0x124a150})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:89 +0x37&#xA;        github.com/stretchr/testify/suite.recoverAndFailOnPanic(0xc0003b2540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:83 +0x35&#xA;        panic({0xb5a3c0?, 0x124a150?})&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:792 +0x132&#xA;        net/http/httptest.(*Server).Close(0x0)&#xA;        &#x9;/usr/local/go/src/net/http/httptest/server.go:203 +0x44&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).TearDownTest(0x124e0e0?)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:151 +0x17&#xA;        github.com/stretchr/testify/suite.Run.func1.1()&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:184 +0x269&#xA;        runtime.Goexit()&#xA;        &#x9;/usr/local/go/src/runtime/panic.go:636 +0x5e&#xA;        testing.(*common).FailNow(0xc0003b2540)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1041 +0x4a&#xA;        github.com/stretchr/testify/require.NoError({0xd316f8, 0xc0003b2540}, {0xd2e8c0, 0xc000313270}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:1357 +0xca&#xA;        github.com/stretchr/testify/require.(*Assertions).NoError(0xc000319560, {0xd2e8c0, 0xc000313270}, {0x0, 0x0, 0x0})&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require_forward.go:1072 +0x9d&#xA;        pkg.world.dev/world-cli/cmd/world/forge.(*ForgeTestSuite).SetupTest(0xc000230700)&#xA;        &#x9;/home/doglightning/world-cli/cmd/world/forge/forge_test.go:54 +0xb3&#xA;        github.com/stretchr/testify/suite.Run.func1(0xc0003b2540)&#xA;        &#x9;/home/doglightning/go/pkg/mod/github.com/stretchr/testify@v1.10.0/suite/suite.go:192 +0x1e5&#xA;        testing.tRunner(0xc0003b2540, 0xc000249050)&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1792 +0xf4&#xA;        created by testing.(*T).Run in goroutine 36&#xA;        &#x9;/usr/local/go/src/testing/testing.go:1851 +0x413&#xA;--- FAIL: TestForgeSuite/TestValidateRepoToken (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/forge" name="TestForgeSuite" time="0.010000">
			<failure message="Failed" type="">=== RUN   TestForgeSuite&#xA;--- FAIL: TestForgeSuite (0.01s)&#xA;</failure>
		</testcase>
	</testsuite>
	<testsuite tests="4" failures="3" time="116.545000" name="pkg.world.dev/world-cli/cmd/world/root" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root" name="TestSubcommandsHaveHelpText" time="0.000000">
			<failure message="Failed" type="">=== RUN   TestSubcommandsHaveHelpText&#xA;    root_test.go:66: assertion failed: count is &lt;= 0: subcommand &#34;cardinal&#34; is not listed in the help command&#xA;    root_test.go:66: assertion failed: count is &lt;= 0: subcommand &#34;doctor&#34; is not listed in the help command&#xA;    root_test.go:66: assertion failed: count is &lt;= 0: subcommand &#34;help&#34; is not listed in the help command&#xA;    root_test.go:66: assertion failed: count is &lt;= 0: subcommand &#34;version&#34; is not listed in the help command&#xA;--- FAIL: TestSubcommandsHaveHelpText (0.00s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root" name="TestCreateStartStopRestartPurge" time="0.840000">
			<failure message="Failed" type="">=== RUN   TestCreateStartStopRestartPurge&#xA;Error: unknown flag: --detach&#xA;Usage:&#xA;&#xA;Flags:&#xA;  -h, --help   help for world&#xA;&#xA;    root_test.go:133: assertion failed: error is not nil: unknown flag: --detach&#xA;--- FAIL: TestCreateStartStopRestartPurge (0.84s)&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root" name="TestDev" time="-0.000000">
			<failure message="Failed" type="">=== RUN   TestDev&#xA;Error: unknown flag: --editor&#xA;Usage:&#xA;&#xA;Flags:&#xA;  -h, --help   help for world&#xA;&#xA;    root_test.go:193: assertion failed: error is not nil: unknown flag: --editor&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;    root_test.go:246: Cardinal is not running, retrying...&#xA;signal: interrupt&#xA;</failure>
		</testcase>
		<testcase classname="pkg.world.dev/world-cli/cmd/world/root" name="TestExecuteDoctorCommand" time="0.420000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.008000" name="pkg.world.dev/world-cli/common" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="14" failures="0" time="0.012000" name="pkg.world.dev/world-cli/common/config" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanSetNamespaceWithFilename" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanSetNamespaceWithEnvVariable" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestConfigPreference" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestConfigFromLocalFile" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestLoadConfigLooksInParentDirectories" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestTextDecoding" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanSetArbitraryEnvVariables" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanOverrideRootDir" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestErrorWhenNoConfigFileExists" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestNumbersAreValidDockerEnvVariable" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestErrorOnInvalidToml" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestDuplicateEnvironmentVariableProducesError" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestCanParseExampleConfig" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/config" name="TestConfigFlagCannotBeEmpty" time="0.000000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.009000" name="pkg.world.dev/world-cli/common/dependency" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="6" failures="0" time="10.708000" name="pkg.world.dev/world-cli/common/docker" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestStart" time="1.980000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestStop" time="2.020000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestRestart" time="2.840000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestPurge" time="1.150000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestStartUndetach" time="2.060000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/docker" name="TestBuild" time="0.620000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.006000" name="pkg.world.dev/world-cli/common/docker/service" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="16" failures="0" time="0.605000" name="pkg.world.dev/world-cli/common/editor" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestSetupCardinalEditor/setup_cardinal_editor" time="0.590000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestSetupCardinalEditor" time="0.590000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestCopyDir/Test_copy_directory" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestCopyDir" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestStrippedGUID/Test_guid_doesn&#39;t_contain_-" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestStrippedGUID" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestAddFileVersion" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion/Module_exists" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion/Module_does_not_exist" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion/go.mod_file_does_not_exist" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetModuleVersion" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestFileExists" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap/successful_response_with_specific_version_map" time="0.010000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap/HTTP_error" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap/invalid_JSON" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/editor" name="TestGetVersionMap" time="0.010000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.008000" name="pkg.world.dev/world-cli/common/globalconfig" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.010000" name="pkg.world.dev/world-cli/common/logger" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="1" failures="0" time="0.007000" name="pkg.world.dev/world-cli/common/login" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/login" name="TestDecryptAccessToken" time="0.000000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.006000" name="pkg.world.dev/world-cli/common/printer" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="11" failures="0" time="0.580000" name="pkg.world.dev/world-cli/common/teacmd" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGitCloneCmd/error_clone_wrong_address" time="0.010000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGitCloneCmd/success" time="0.560000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGitCloneCmd" time="0.570000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml/append_first_section_and_fields" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml/append_fields_to_existing_section" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml/create_new_section_and_append_fields" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestAppendToToml" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString/length_0" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString/length_8" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString/length_16" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/teacmd" name="TestGenerateRandomHexString" time="0.000000"></testcase>
	</testsuite>
	<testsuite tests="6" failures="0" time="0.013000" name="pkg.world.dev/world-cli/common/tomlutil" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestCreateTOMLFile" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestGetTOMLSection" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestReadTOML" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestUpdateTOMLSection" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite/TestWriteTOML" time="0.000000"></testcase>
		<testcase classname="pkg.world.dev/world-cli/common/tomlutil" name="TestTOMLSuite" time="0.010000"></testcase>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.006000" name="pkg.world.dev/world-cli/gen/logs/v1" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.010000" name="pkg.world.dev/world-cli/gen/logs/v1/logsv1connect" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.007000" name="pkg.world.dev/world-cli/tea/component" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.006000" name="pkg.world.dev/world-cli/tea/component/multiselect" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.010000" name="pkg.world.dev/world-cli/tea/component/multispinner" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/tea/component/program" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/tea/component/spinner" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/tea/component/steps" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/tea/style" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
	<testsuite tests="0" failures="0" time="0.004000" name="pkg.world.dev/world-cli/telemetry" timestamp="2025-05-06T12:43:45-04:00">
		<properties>
			<property name="go.version" value="go1.24.1 linux/amd64"></property>
		</properties>
	</testsuite>
</testsuites>